[package]
authors = ["iqlusion"]
edition = "2018"
license = "Apache-2.0 OR MIT"
name    = "runner"
publish = false
version = "0.0.0"

[dependencies]
serialport = { version = "3.3.0", default-features = false }
xmodem = "0.1.3"
