[package]
authors = ["iqlusion"]
edition = "2018"
license = "Apache-2.0 OR MIT"
name    = "memlog"
version = "0.0.0"

[dependencies.pac]
features = ["gicc"]
package = "imx6ul-pac"
path = "../imx6ul-pac"