[package]
authors = ["iqlusion"]
edition = "2018"
license = "Apache-2.0 OR MIT"
name = "panic-serial"
version = "0.0.0"

[dependencies]
cortex-a = { path = "../cortex-a" }
usbarmory = { path = "../usbarmory" }
