[package]
authors = ["iqlusion"]
edition = "2018"
license = "Apache-2.0 OR MIT"
name    = "cortex-a-rtic-macros"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.7"
quote = "1.0.2"
rtic-syntax = "0.4.0"
syn = "1.0.13"
