[workspace]
members = [
  "cortex-a",
  "cortex-a-rtfm",
  "exception-reset",
  "imx6ul-pac",
  "memlog",
  "panic-serial",
  "usbarmory",
  "usbarmory-rt",
]

[profile.release]
lto = true
codegen-units = 1